### ISSUE TITLE
Undefined method `state' for #<Post not initialized> error

### ISSUE THREAD

**Issue by huoxito** [state-machines/state_machines-activerecord#2]
Been trying to make [spree run with this project](https://github.com/huoxito/state_machines-activerecord/commit/0b1ad2091ea101555f8c454d26ff272cafcbbc84) and noticed that every time I point the Gemfile to git or the gem release I get an error like this `Undefined method 'state' for #<Post not initialized>` (tested on a bran new rails project as well). Whenever I point to the code using `path` (local code) it works fine though. Have you experienced anything similar? (I might have something wrong in my local bundle config or set up and I can't see it right now)

For some reason the activerecord object is being initialized using the `Machine#initialize` method rather than the `ActiveRecord#initialize`.

To reproduce put a state machine on an activerecord object, e.g.:

```ruby
class Post < ActiveRecord::Base
  state_machine initial: :draft do
    event :review do
      transition to: :reviwed, from: :draft
    end

    event :complete do
      transition to: :completed
    end
  end
end
```

Open rails c and then `Post.new`. 

Full stack trace of the error:

```
NoMethodError: undefined method `state' for #<Post not initialized>
        from /Users/huoxito/.gem/ruby/2.1.3/gems/activemodel-4.2.0/lib/active_model/attribute_methods.rb:433:in `method_missing'
        from /Users/huoxito/.gem/ruby/2.1.3/gems/state_machines-0.1.0/lib/state_machines/machine.rb:1053:in `read'
        from /Users/huoxito/.gem/ruby/2.1.3/gems/state_machines-0.1.0/lib/state_machines/machine.rb:1904:in `initialize_state?'
        from /Users/huoxito/.gem/ruby/2.1.3/bundler/gems/state_machines-activerecord-041af9e52445/lib/state_machines/integrations/active_record.rb:573:in `initialize_state'
        from /Users/huoxito/.gem/ruby/2.1.3/gems/state_machines-0.1.0/lib/state_machines/machine_collection.rb:29:in `block in initialize_states'
        from /Users/huoxito/.gem/ruby/2.1.3/gems/state_machines-0.1.0/lib/state_machines/machine_collection.rb:28:in `each_value'
        from /Users/huoxito/.gem/ruby/2.1.3/gems/state_machines-0.1.0/lib/state_machines/machine_collection.rb:28:in `initialize_states'
        from /Users/huoxito/.gem/ruby/2.1.3/gems/state_machines-0.1.0/lib/state_machines/machine.rb:1925:in `initialize'
        from /Users/huoxito/.gem/ruby/2.1.3/gems/activerecord-4.2.0/lib/active_record/inheritance.rb:61:in `new'
        from /Users/huoxito/.gem/ruby/2.1.3/gems/activerecord-4.2.0/lib/active_record/inheritance.rb:61:in `new'
        from (irb):1
        from /Users/huoxito/.gem/ruby/2.1.3/gems/railties-4.2.0/lib/rails/commands/console.rb:110:in `start'
        from /Users/huoxito/.gem/ruby/2.1.3/gems/railties-4.2.0/lib/rails/commands/console.rb:9:in `start'
        from /Users/huoxito/.gem/ruby/2.1.3/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:68:in `console'
        from /Users/huoxito/.gem/ruby/2.1.3/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /Users/huoxito/.gem/ruby/2.1.3/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:8:in `require'
        from bin/rails:8:in `<main>'irb(main):002:0>
```

**Comment by huoxito** [comment]
@seuros I think it is missing this [piece from the old gem](https://github.com/spree-contrib/state_machine/blob/00822c4b6d3df347087ef80e34a028f19325b342/lib/state_machine/integrations.rb#L116-119). It needs to make sure that ActiveModel is the last item on the `integrations` list. Or it needs to change the way the [Integration class is fetched](https://github.com/state-machines/state_machines/blob/9a5d814ab2c9f3277e4e8a777e6e3d58cb3d1770/lib/state_machines/machine.rb#L507) to properly match activerecord classes (rather than activemodel that will always be included in activerecord).

**Comment by seuros** [comment]
I will fix this.

**Comment by seuros** [comment]
@huoxito could you try again. I pushed some fixes.

btw : ```2 failures, 4 errors, 0 skips ``` :smile_cat:

**Comment by huoxito** [comment]
thanks @seuros, the `reverse` you did on state_machines had it fixed, personally I'd prefer checking explicitly for "ActiveModel" and putting it last on the list just to make sure it doesn't get back at us again. Either way all cool now both using github and local path. cheers

**Comment by seuros** [comment]
I reversed that change since it was placing AM at the top .
I fixed it with https://github.com/state-machines/state_machines/commit/413182d249c25b32c918a21b6b3c80f6350d9b67.

**Comment by seuros** [comment]
I agreed with you, we need to find a way to place integrations after their dependency.
 We could remove the autoregister of namespaced integrations and register them manually with ```Integrations#register```.
Let me know when you want a release in Rubygems, the gem is stable enough to be tested.

**Comment by huoxito** [comment]
@seuros actually I'm still seeing a ton of errors related to this on spree build, could we have a more explicit version of that method (just like the original gem had)? e.g.

```ruby
def name_spaced_integrations
  # FIXME, Integrations should be add before their dependencies.
  constants = self.constants.map {|c| c.to_s}.select {|c| c != 'ActiveModel' }.sort << 'ActiveModel'
  constants.each do |const|
    integration = self.const_get(const)
    add(integration)
  end
end
```

btw this is pretty hard for me to debug and figure out whats going on suggest a solution

Also I dont understand the change in https://github.com/state-machines/state_machines/commit/413182d249c25b32c918a21b6b3c80f6350d9b67 but if I revert it I get less errors as well. Overall splitting the gem into multiple projects seems to have made things more complicated, might take a while to figure exactly how to best address these issues.
